name: Package and Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    name: Package and Release
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and Release
        uses: BigWigsMods/packager@v2
